version: '3'

services:
  banners-postgres:
    image: postgres:alpine
    ports:
      - "22413:5432"
    environment:
      - POSTGRES_USER=scilightener
      - POSTGRES_PASSWORD=hell12345678yeah
      - POSTGRES_DB=banners-task

  banners-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: >
      sh -c "echo 'user scilightener on >12345678 ~* &* +@all' > /tmp/redis-users.acl && 
            echo 'user default off' >> /tmp/redis-users.acl && 
            redis-server --aclfile /tmp/redis-users.acl"
