name: test
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Install make
        run: |
          apt-get update
          apt-get install -y make

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1

      - name: Export GOPATH/bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Install make
        run: |
          apt-get update
          apt-get install -y make

      - name: Install docker-compose
        run: apt-get install -y docker-compose

      - name: Run Tests
        run: make test

#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: '1.22.1'
#
#      - name: Verify Go installation
#        run: go version
#
#      - name: Install make
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y make
#
#      - name: Install golangci-lint
#        run: |
#          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1
#
#      - name: Export GOPATH/bin to PATH
#        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
#
#      - name: Verify golangci-lint installation
#        run: golangci-lint --version
#
#      - name: Install docker-compose
#        run: sudo apt-get install -y docker-compose
#
#      - name: Verify docker-compose installation
#        run: docker-compose version
#
#      - name: Run linting
#        run: make lint
#
#      - name: Run tests
#        run: make test